// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inxewyouvglsogcwivfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlueGV3eW91dmdsc29nY3dpdmZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Njk4NTQsImV4cCI6MjA2NzU0NTg1NH0.nqVT32X6p15AaZIyM0DNHYedRdphwhERiFNjW4lkh5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});